### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by mcollina** [lyquocnam/fastify-sequelize#2]
unit tests are missing

**Comment by lyquocnam** [comment]
i never use unit tests before, please show me some info @@

**Comment by mcollina** [comment]
Have a look at: https://github.com/fastify/fastify-mongodb/blob/master/test.js

**Comment by lyquocnam** [comment]
i just added here @mcollina  https://github.com/lyquocnam/fastify-sequelize/commit/a2968e72f55a80a315da321079c98293e75211bb
